services:
  subscribe-database:
    image: mongo
    volumes:
      - mongo-data:/data/db

  subscribe-backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=mongodb://subscribe-database:27017/ThaZoneDev
    ports:
      - "3000:3000"
    depends_on:
      - subscribe-database

  subscribe-frontend:
    build:
      context: ./client
      args:
        - REACT_APP_BACKEND_URL=http://subscribe-backend:3000
    ports:
      - "3001:80"
    depends_on:
      - subscribe-backend