services:
  subscribe-database:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - default  # Use the default network

    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    sysctls:
      net.core.somaxconn: 1024
      fs.file-max: 65535
      vm.swappiness: 1

  subscribe-backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://172.18.0.2:27017/ThaZoneDev  # Use the existing IP
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - subscribe-database
    networks:
      - default

  subscribe-frontend:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=http://subscribe-backend:3000
    ports:
      - "3001:80"
    volumes:
      - ./client:/app
    depends_on:
      - subscribe-backend
    networks:
      - default

volumes:
  mongo-data:

networks:
  simpleweb_default:
    external: true

