services:
  subscribe-database:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
      
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  subscribe-backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://subscribe-database:27017/ThaZoneDev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - subscribe-database

  subscribe-frontend:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=http://subscribe-backend:3000
    ports:
      - "3001:80"
    volumes:
      - ./client:/app
    depends_on:
      - subscribe-backend

volumes:
  mongo-data:
